apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-hpserver-pvc
  namespace: jenkins-hpserver
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
