apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-hpserver
  namespace: jenkins-hpserver
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /

